OrdererOrgs:
  - Name: Orderer
    Domain: medichain.com
    Specs:
      - Hostname: orderer
      - Hostname: orderer2
      - Hostname: orderer3
      - Hostname: orderer4
      - Hostname: orderer5

PeerOrgs:
  - Name: Doctor
    Domain: doctor.medichain.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
      
  - Name: Hospital
    Domain: hospital.medichain.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
  
  - Name: Laboratory
    Domain: laboratory.medichain.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1

  - Name: Pharmacy
    Domain: pharmacy.medichain.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1

  - Name: Healthinsurer
    Domain: healthinsurer.medichain.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
