# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.medichain.com:
    container_name: orderer.medichain.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/medichain.com/orderers/orderer.medichain.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/medichain.com/orderers/orderer.medichain.com/tls/:/var/hyperledger/orderer/tls
        - orderer.medichain.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.doctor.medichain.com:
    container_name: peer0.doctor.medichain.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.doctor.medichain.com
      - CORE_PEER_ADDRESS=peer0.doctor.medichain.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.doctor.medichain.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.doctor.medichain.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.doctor.medichain.com:7051
      - CORE_PEER_LOCALMSPID=DoctorMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/doctor.medichain.com/peers/peer0.doctor.medichain.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/doctor.medichain.com/peers/peer0.doctor.medichain.com/tls:/etc/hyperledger/fabric/tls
        - peer0.doctor.medichain.com:/var/hyperledger/production
    ports:
      - 7051:7051

  peer1.doctor.medichain.com:
    container_name: peer1.doctor.medichain.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.doctor.medichain.com
      - CORE_PEER_ADDRESS=peer1.doctor.medichain.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.doctor.medichain.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.doctor.medichain.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.doctor.medichain.com:7051
      - CORE_PEER_LOCALMSPID=DoctorMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/doctor.medichain.com/peers/peer1.doctor.medichain.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/doctor.medichain.com/peers/peer1.doctor.medichain.com/tls:/etc/hyperledger/fabric/tls
        - peer1.doctor.medichain.com:/var/hyperledger/production

    ports:
      - 8051:8051

  peer0.hospital.medichain.com:
    container_name: peer0.hospital.medichain.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.hospital.medichain.com
      - CORE_PEER_ADDRESS=peer0.hospital.medichain.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.hospital.medichain.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.hospital.medichain.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.hospital.medichain.com:10051
      - CORE_PEER_LOCALMSPID=HospitalMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/hospital.medichain.com/peers/peer0.hospital.medichain.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/hospital.medichain.com/peers/peer0.hospital.medichain.com/tls:/etc/hyperledger/fabric/tls
        - peer0.hospital.medichain.com:/var/hyperledger/production
    ports:
      - 9051:9051

  peer1.hospital.medichain.com:
    container_name: peer1.hospital.medichain.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.hospital.medichain.com
      - CORE_PEER_ADDRESS=peer1.hospital.medichain.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer1.hospital.medichain.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.hospital.medichain.com:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.hospital.medichain.com:9051
      - CORE_PEER_LOCALMSPID=HospitalMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/hospital.medichain.com/peers/peer1.hospital.medichain.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/hospital.medichain.com/peers/peer1.hospital.medichain.com/tls:/etc/hyperledger/fabric/tls
        - peer1.hospital.medichain.com:/var/hyperledger/production
    ports:
      - 10051:10051

  peer0.laboratory.medichain.com:
    container_name: peer0.laboratory.medichain.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.laboratory.medichain.com
      - CORE_PEER_ADDRESS=peer0.laboratory.medichain.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.laboratory.medichain.com:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.laboratory.medichain.com:11051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.laboratory.medichain.com:12051
      - CORE_PEER_LOCALMSPID=LaboratoryMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/laboratory.medichain.com/peers/peer0.laboratory.medichain.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/laboratory.medichain.com/peers/peer0.laboratory.medichain.com/tls:/etc/hyperledger/fabric/tls
        - peer0.laboratory.medichain.com:/var/hyperledger/production
    ports:
      - 11051:11051

  peer1.laboratory.medichain.com:
    container_name: peer1.laboratory.medichain.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.laboratory.medichain.com
      - CORE_PEER_ADDRESS=peer1.laboratory.medichain.com:12051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:12051
      - CORE_PEER_CHAINCODEADDRESS=peer1.laboratory.medichain.com:12052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:12052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.laboratory.medichain.com:12051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.laboratory.medichain.com:11051
      - CORE_PEER_LOCALMSPID=LaboratoryMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/laboratory.medichain.com/peers/peer1.laboratory.medichain.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/laboratory.medichain.com/peers/peer1.laboratory.medichain.com/tls:/etc/hyperledger/fabric/tls
        - peer1.laboratory.medichain.com:/var/hyperledger/production
    ports:
      - 12051:12051

  peer0.pharmacy.medichain.com:
    container_name: peer0.pharmacy.medichain.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.pharmacy.medichain.com
      - CORE_PEER_ADDRESS=peer0.pharmacy.medichain.com:13051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:13051
      - CORE_PEER_CHAINCODEADDRESS=peer0.pharmacy.medichain.com:13052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:13052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.pharmacy.medichain.com:13051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.pharmacy.medichain.com:14051
      - CORE_PEER_LOCALMSPID=PharmacyMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/pharmacy.medichain.com/peers/peer0.pharmacy.medichain.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/pharmacy.medichain.com/peers/peer0.pharmacy.medichain.com/tls:/etc/hyperledger/fabric/tls
        - peer0.pharmacy.medichain.com:/var/hyperledger/production
    ports:
      - 13051:13051

  peer1.pharmacy.medichain.com:
    container_name: peer1.pharmacy.medichain.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.pharmacy.medichain.com
      - CORE_PEER_ADDRESS=peer1.pharmacy.medichain.com:14051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:14051
      - CORE_PEER_CHAINCODEADDRESS=peer1.pharmacy.medichain.com:14052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:14052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.pharmacy.medichain.com:14051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.pharmacy.medichain.com:13051
      - CORE_PEER_LOCALMSPID=PharmacyMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/pharmacy.medichain.com/peers/peer1.pharmacy.medichain.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/pharmacy.medichain.com/peers/peer1.pharmacy.medichain.com/tls:/etc/hyperledger/fabric/tls
        - peer1.pharmacy.medichain.com:/var/hyperledger/production
    ports:
      - 14051:14051

  peer0.healthinsurer.medichain.com:
    container_name: peer0.healthinsurer.medichain.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.healthinsurer.medichain.com
      - CORE_PEER_ADDRESS=peer0.healthinsurer.medichain.com:15051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:15051
      - CORE_PEER_CHAINCODEADDRESS=peer0.healthinsurer.medichain.com:15052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:15052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.healthinsurer.medichain.com:15051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.healthinsurer.medichain.com:16051
      - CORE_PEER_LOCALMSPID=HealthinsurerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/healthinsurer.medichain.com/peers/peer0.healthinsurer.medichain.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/healthinsurer.medichain.com/peers/peer0.healthinsurer.medichain.com/tls:/etc/hyperledger/fabric/tls
        - peer0.healthinsurer.medichain.com:/var/hyperledger/production
    ports:
      - 15051:15051

  peer1.healthinsurer.medichain.com:
    container_name: peer1.healthinsurer.medichain.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.healthinsurer.medichain.com
      - CORE_PEER_ADDRESS=peer1.healthinsurer.medichain.com:16051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:16051
      - CORE_PEER_CHAINCODEADDRESS=peer1.healthinsurer.medichain.com:16052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:16052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.healthinsurer.medichain.com:16051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.healthinsurer.medichain.com:15051
      - CORE_PEER_LOCALMSPID=HealthinsurerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/healthinsurer.medichain.com/peers/peer1.healthinsurer.medichain.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/healthinsurer.medichain.com/peers/peer1.healthinsurer.medichain.com/tls:/etc/hyperledger/fabric/tls
        - peer1.healthinsurer.medichain.com:/var/hyperledger/production
    ports:
      - 16051:16051
